# Generated by Django 4.2 on 2023-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_chek',
            field=models.BooleanField(default=False),
        ),
    ]
